name: Build AccountingHub Desktop + MSI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore AccountingHub.sln

      - name: Build
        run: dotnet build AccountingHub.sln -c Release --no-restore

      - name: Publish desktop app
        run: dotnet publish AccountingHub.Desktop -c Release -o publish

      - name: Install WiX Toolset
        run: dotnet tool install --global wix --version 4.0.1

      - name: Build MSI Installer
        working-directory: Installer
        run: wix build AccountingHub.wixproj -o AccountingHub.msi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: AccountingHub-MSI
          path: Installer/AccountingHub.msi
