<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">

  <Package
      Name="AccountingHub"
      Version="1.0.0"
      Manufacturer="JJ Software"
      UpgradeCode="C7B0E03C-3E15-4E8A-9A77-8EAB2C6B7031"
      InstallerVersion="500"
      Scope="perMachine">

    <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />

    <Feature Id="MainFeature" Title="AccountingHub" Level="1">
      <ComponentGroupRef Id="ProductComponents" />
      <ComponentRef Id="StartMenuShortcut" />
    </Feature>
  </Package>

  <!-- ================== Directories ================== -->
  <Fragment>
    <StandardDirectory Id="ProgramFilesFolder">
      <Directory Id="INSTALLFOLDER" Name="AccountingHub" />
    </StandardDirectory>

    <StandardDirectory Id="ProgramMenuFolder">
      <Directory Id="ApplicationProgramsFolder" Name="AccountingHub" />
    </StandardDirectory>
  </Fragment>

  <!-- ================== Components ================== -->
  <Fragment>
    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
      <Component Id="MainFiles" Directory="INSTALLFOLDER">
        <File Source="publish\AccountingHub.Desktop.exe" />
        <File Source="publish\AccountingHub.Desktop.dll" />
        <File Source="publish\AccountingHub.Domain.dll" />
        <File Source="publish\AccountingHub.Infrastructure.dll" />
        <File Source="publish\AccountingHub.Payroll.dll" />
        <File Source="publish\AccountingHub.Desktop.deps.json" />
        <File Source="publish\AccountingHub.Desktop.runtimeconfig.json" />
      </Component>
    </ComponentGroup>

    <Component Id="StartMenuShortcut" Directory="ApplicationProgramsFolder">
      <Shortcut
        Id="AppShortcut"
        Name="AccountingHub"
        Target="[INSTALLFOLDER]AccountingHub.Desktop.exe"
        Description="AccountingHub Desktop Application"
        WorkingDirectory="INSTALLFOLDER" />
      <RemoveFolder Id="RemoveShortcutFolder" On="uninstall" />
      <RegistryValue
        Root="HKCU"
        Key="Software\JJSoftware\AccountingHub"
        Name="installed"
        Type="integer"
        Value="1"
        KeyPath="yes" />
    </Component>
  </Fragment>

</Wix>
