name: Build AccountingHub MSI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish desktop app
      run: |
        dotnet publish AccountingHub.Desktop -c Release -o Installer/publish

    - name: Install WiX Toolset
      run: choco install wixtoolset --yes

    - name: Build MSI Installer
      working-directory: Installer
      run: wix build Product.wxs -o AccountingHub.msi

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: AccountingHub-MSI
        path: Installer/AccountingHub.msi
