name: Build Windows App & MSI

on:
  push:
    branches:
      - main

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore AccountingHub.sln

      - name: Build project
        run: dotnet build AccountingHub.sln -c Release

      - name: Publish desktop app
        run: |
          dotnet publish AccountingHub.Desktop/AccountingHub.Desktop.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false -o Installer/publish

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset --version=3.11.2 -y
          echo "PATH after WiX install:"
          echo "$env:PATH"
          echo "WiX installation complete"

      - name: Add WiX to PATH
        run: |
          $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          echo "WiX path added to environment"
          heat dir Installer/publish -cg ProductComponents -dr INSTALLFOLDER -var var.SourceDir -out Installer/Files.wxs

      - name: Build MSI
        run: |
          candle.exe Installer\Product.wxs Installer\Files.wxs -dVersion=${{ env.VERSION }} -ext WixUtilExtension
          light.exe Installer\Product.wixobj Installer\Files.wixobj -ext WixUIExtension -o AccountingHub-${{ env.VERSION }}.msi

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: AccountingHub-MSI
          path: AccountingHub-${{ env.VERSION }}.msi
