name: Build Windows App & MSI

on:
  push:
    branches:
      - main

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore AccountingHub.sln

      - name: Build project
        run: dotnet build AccountingHub.sln -c Release

      - name: Publish desktop app
        run: |
          dotnet publish AccountingHub.Desktop/AccountingHub.Desktop.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false -o Installer/publish

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset --version=4.0.4 -y
          echo "WiX installed successfully"

      - name: Generate Files.wxs from publish folder
        run: |
          wix convert Installer/publish -o Installer/Files.wxs

      - name: Build MSI
        run: |
          wix build Installer/Product.wxs Installer/Files.wxs -define Version=${{ env.VERSION }} -o AccountingHub-${{ env.VERSION }}.msi --ext WixToolset.UI.wixext --bind-path Installer/publish

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: AccountingHub-MSI
          path: AccountingHub-${{ env.VERSION }}.msi

      - name: Post Setup .NET
        if: always()
        run: dotnet --info
