name: Build AccountingHub MSI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish desktop app
      run: |
        dotnet publish AccountingHub.Desktop -c Release -o Installer/publish

    - name: Install WiX v4 CLI
      run: dotnet tool install --global wix --version 4.0.4

    - name: Add WiX to PATH
      run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

    - name: Set build version
      id: version
      run: echo "VERSION=1.0.$(date +'%y%m%d%H%M')" >> $GITHUB_ENV

    - name: Build MSI Installer
      working-directory: Installer
      run: wix build Product.wxs -define Version=${{ env.VERSION }} -o AccountingHub-${{ env.VERSION }}.msi

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: AccountingHub-${{ env.VERSION }}
        path: Installer/AccountingHub-${{ env.VERSION }}.msi
