name: Build AccountingHub MSI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish AccountingHub.Desktop -c Release -r win-x64 --self-contained false

      - name: Ensure WiX Toolset Installed
        run: |
          choco install wixtoolset -y --force --allow-downgrade || echo "WiX already installed"

      - name: Add WiX to PATH
        run: |
          $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.14\bin"
          echo "##vso[task.prependpath]C:\Program Files (x86)\WiX Toolset v3.14\bin"

      - name: Build MSI
        run: |
          cd Installer
          candle Product.wxs Files.wxs -dProjectDir="D:\a\AccountingHub\AccountingHub"
          light Product.wixobj Files.wixobj -out AccountingHub.msi

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AccountingHub-Installer
          path: Installer/AccountingHub.msi
